### ISSUE TITLE
Stop logging warning when enum value is nil

### ISSUE THREAD

**Issue by peter-wilkins-mayden** [workframers/stillsuit#14]
Hi, great work with this project.
I have an enum field that is nullable in the graphql schema.
When it is null it logs this warning:
`WARN  stillsuit.core - Unable to find datomic enum equivalent for lacinia enum value null!`
could the log level be changed to INFO?
or is there something I should be doing in my application.
thanks
ps. any chance you will release v0.13 to clojars?

**Comment by timgilbert** [comment]
Hi, thanks @peter-wilkins-mayden. I'll make that change and push another release, hopefully later today some time.

**Comment by timgilbert** [comment]
I just merged in the change and uploaded it to Clojars as `0.13.0`. Thanks for the report!
